<?php namespace App\Models;
// generated from /resources/views/vendor/survloop/admin/db/export-laravel-model-gen.blade.php

use Illuminate\Database\Eloquent\Model;

class RIICaWaterBoard extends Model
{
    protected $table      = 'rii_ca_water_board';
    protected $primaryKey = 'ca_wa_bo_id';
    public $timestamps    = true;
    protected $fillable   = 
    [    
		'ca_wa_bo_cultivation_type_confirmed', 
		'ca_wa_bo_date', 
		'ca_wa_bo_farm_name', 
		'ca_wa_bo_year', 
		'ca_wa_bo_reporting', 
		'ca_wa_bo_county', 
		'ca_wa_bo_outdoor_canopy_area', 
		'ca_wa_bo_outdoor_plant_count', 
		'ca_wa_bo_outdoor_growing_medium', 
		'ca_wa_bo_mixed_light_canopy_area', 
		'ca_wa_bo_mixed_light_plant_count', 
		'ca_wa_bo_mixed_light_growing_medium', 
		'ca_wa_bo_indoor_canopy_area', 
		'ca_wa_bo_indoor_plant_count', 
		'ca_wa_bo_indoor_growing_medium', 
		'ca_wa_bo_total_canopy_area', 
		'ca_wa_bo_water_storage_cap_gal', 
		'ca_wa_bo_water_storage_source_1', 
		'ca_wa_bo_water_stored_source_1_jan', 
		'ca_wa_bo_water_stored_source_1_feb', 
		'ca_wa_bo_water_stored_source_1_mar', 
		'ca_wa_bo_water_stored_source_1_apr', 
		'ca_wa_bo_water_stored_source_1_may', 
		'ca_wa_bo_water_stored_source_1_jun', 
		'ca_wa_bo_water_stored_source_1_jul', 
		'ca_wa_bo_water_stored_source_1_aug', 
		'ca_wa_bo_water_stored_source_1_sep', 
		'ca_wa_bo_water_stored_source_1_oct', 
		'ca_wa_bo_water_stored_source_1_nov', 
		'ca_wa_bo_water_stored_source_1_dec', 
		'ca_wa_bo_water_storage_source_2', 
		'ca_wa_bo_water_stored_source_2_jan', 
		'ca_wa_bo_water_stored_source_2_feb', 
		'ca_wa_bo_water_stored_source_2_mar', 
		'ca_wa_bo_water_stored_source_2_apr', 
		'ca_wa_bo_water_stored_source_2_may', 
		'ca_wa_bo_water_stored_source_2_jun', 
		'ca_wa_bo_water_stored_source_2_jul', 
		'ca_wa_bo_water_stored_source_2_aug', 
		'ca_wa_bo_water_stored_source_2_sep', 
		'ca_wa_bo_water_stored_source_2_oct', 
		'ca_wa_bo_water_stored_source_2_nov', 
		'ca_wa_bo_water_stored_source_2_dec', 
		'ca_wa_bo_water_storage_source_3', 
		'ca_wa_bo_water_stored_source_3_jan', 
		'ca_wa_bo_water_stored_source_3_feb', 
		'ca_wa_bo_water_stored_source_3_mar', 
		'ca_wa_bo_water_stored_source_3_apr', 
		'ca_wa_bo_water_stored_source_3_may', 
		'ca_wa_bo_water_stored_source_3_jun', 
		'ca_wa_bo_water_stored_source_3_jul', 
		'ca_wa_bo_water_stored_source_3_aug', 
		'ca_wa_bo_water_stored_source_3_sep', 
		'ca_wa_bo_water_stored_source_3_oct', 
		'ca_wa_bo_water_stored_source_3_nov', 
		'ca_wa_bo_water_stored_source_3_dec', 
		'ca_wa_bo_water_application_source_1', 
		'ca_wa_bo_water_applied_source_1_jan', 
		'ca_wa_bo_water_applied_source_1_feb', 
		'ca_wa_bo_water_applied_source_1_mar', 
		'ca_wa_bo_water_applied_source_1_apr', 
		'ca_wa_bo_water_applied_source_1_may', 
		'ca_wa_bo_water_applied_source_1_jun', 
		'ca_wa_bo_water_applied_source_1_jul', 
		'ca_wa_bo_water_applied_source_1_aug', 
		'ca_wa_bo_water_applied_source_1_sep', 
		'ca_wa_bo_water_applied_source_1_oct', 
		'ca_wa_bo_water_applied_source_1_nov', 
		'ca_wa_bo_water_applied_source_1_dec', 
		'ca_wa_bo_water_application_source_2', 
		'ca_wa_bo_water_applied_source_2_jan', 
		'ca_wa_bo_water_applied_source_2_feb', 
		'ca_wa_bo_water_applied_source_2_mar', 
		'ca_wa_bo_water_applied_source_2_apr', 
		'ca_wa_bo_water_applied_source_2_may', 
		'ca_wa_bo_water_applied_source_2_jun', 
		'ca_wa_bo_water_applied_source_2_jul', 
		'ca_wa_bo_water_applied_source_2_aug', 
		'ca_wa_bo_water_applied_source_2_sep', 
		'ca_wa_bo_water_applied_source_2_oct', 
		'ca_wa_bo_water_applied_source_2_nov', 
		'ca_wa_bo_water_applied_source_2_dec', 
		'ca_wa_bo_water_application_source_3', 
		'ca_wa_bo_water_applied_source_3_jan', 
		'ca_wa_bo_water_applied_source_3_feb', 
		'ca_wa_bo_water_applied_source_3_mar', 
		'ca_wa_bo_water_applied_source_3_apr', 
		'ca_wa_bo_water_applied_source_3_may', 
		'ca_wa_bo_water_applied_source_3_jun', 
		'ca_wa_bo_water_applied_source_3_jul', 
		'ca_wa_bo_water_applied_source_3_aug', 
		'ca_wa_bo_water_applied_source_3_sep', 
		'ca_wa_bo_water_applied_source_3_oct', 
		'ca_wa_bo_water_applied_source_3_nov', 
		'ca_wa_bo_water_applied_source_3_dec', 
		'ca_wa_bo_other_water_source', 
		'ca_wa_bo_water_use_estimation_method', 
    ];
    
    // END Survloop auto-generated portion of Model
    
}
