<?php namespace App\Models;
// generated from /resources/views/vendor/survloop/admin/db/export-laravel-model-gen.blade.php

use Illuminate\Database\Eloquent\Model;

class RIIPowerScore extends Model
{
    protected $table      = 'RII_PowerScore';
    protected $primaryKey = 'PsID';
    public $timestamps    = true;
    protected $fillable   = 
    [    
		'PsUserID', 
		'PsStatus', 
		'PsTimeType', 
		'PsPrivacy', 
		'PsZipCode', 
		'PsCounty', 
		'PsState', 
		'PsCountry', 
		'PsAshrae', 
		'PsEmail', 
		'PsNewsletter', 
		'PsMemberInterest', 
		'PsName', 
		'PsCharacterize', 
		'PsEfficOverSimilar',
		'PsEfficOverall', 
		'PsEfficFacility', 
		'PsEfficProduction', 
		'PsEfficLighting', 
		'PsEfficLightingMother', 
		'PsEfficLightingClone', 
		'PsEfficLightingVeg', 
		'PsEfficLightingFlower', 
		'PsEfficHvac', 
		'PsGrams', 
		'PsKWH', 
		'PsTotalSize', 
		'PsHavestsPerYear', 
		'PsHarvestBatch', 
		'PsHasWaterPump', 
		'PsCuresIndoor', 
		'PsCuresOutdoor', 
		'PsCuresOffsite', 
		'PsIsIntegrated', 
		'PsSourceUtility', 
		'PsSourceRenew', 
		'PsOtherPower', 
		'PsIncentiveUsed', 
		'PsIncentiveWants', 
		'PsMotherLoc', 
		'PsProcessingOnsite', 
		'PsSourceUtilityOther', 
		'PsVerticalStack', 
		'PsConsiderUpgrade', 
		'PsUploadEnergyBills', 
		'PsEnergyNonFarm', 
		'PsEnergyNonFarmPerc', 
		'PsHvacOther', 
		'PsHeatWater', 
		'PsExtractingOnsite', 
		'PsControls', 
		'PsControlsAuto', 
		'PsFeedback1', 
		'PsFeedback2', 
		'PsFeedback3', 
		'PsFeedback4', 
		'PsFeedback5', 
		'PsFeedback6', 
		'PsFeedback7', 
		'PsFeedback8', 
		'PsUniqueness1', 
		'PsUniqueness2', 
		'PsUniqueness3', 
		'PsUniqueness4', 
		'PsUniqueness5', 
		'PsUniqueness6', 
		'PsUniqueness7', 
		'PsUniqueness8', 
		'PsIPaddy', 
		'PsUniqueStr', 
		'PsTreeVersion', 
		'PsVersionAB', 
		'PsIsMobile', 
		'PsSubmissionProgress', 
    ];
    
    // END SurvLoop auto-generated portion of Model
    
}
