<?php namespace App\Models;
// generated from /resources/views/vendor/survloop/admin/db/export-laravel-model-gen.blade.php

use Illuminate\Database\Eloquent\Model;

class RIIPowerscore extends Model
{
    protected $table      = 'rii_powerscore';
    protected $primaryKey = 'ps_id';
    public $timestamps    = true;
    protected $fillable   = 
    [    
		'ps_user_id', 
		'ps_status', 
		'ps_is_pro', 
		'ps_time_type', 
		'ps_year', 
		'ps_privacy', 
		'ps_zip_code', 
		'ps_county', 
		'ps_state', 
		'ps_country', 
		'ps_ashrae', 
		'ps_climate_label', 
		'ps_email', 
		'ps_name', 
		'ps_characterize', 
		'ps_effic_overall', 
		'ps_effic_over_similar', 
		'ps_effic_facility', 
		'ps_effic_facility_status', 
		'ps_effic_production', 
		'ps_effic_production_status', 
		'ps_effic_lighting', 
		'ps_effic_lighting_status', 
		'ps_effic_hvac', 
		'ps_effic_hvac_status', 
		'ps_effic_water', 
		'ps_effic_water_status', 
		'ps_effic_waste', 
		'ps_effic_waste_status', 
		'ps_effic_non_electric', 
		'ps_effic_non_electric_status', 
		'ps_grams', 
		'ps_kwh', 
		'ps_total_size', 
		'ps_total_canopy_size', 
		'ps_harvests_per_year', 
		'ps_harvest_batch', 
		'ps_has_water_pump', 
		'ps_is_integrated', 
		'ps_source_utility', 
		'ps_source_renew', 
		'ps_other_power', 
		'ps_mother_loc', 
		'ps_source_utility_other', 
		'ps_vertical_stack', 
		'ps_upload_energy_bills', 
		'ps_energy_non_farm', 
		'ps_energy_non_farm_perc', 
		'ps_hvac_other', 
		'ps_heat_water', 
		'ps_controls', 
		'ps_controls_auto', 
		'ps_ip_addy', 
		'ps_unique_str', 
		'ps_tree_version', 
		'ps_version_ab', 
		'ps_is_mobile', 
		'ps_submission_progress', 
		'ps_notes', 
		'ps_green_waste_lbs', 
		'ps_green_waste_mixed', 
		'ps_compliance_waste_track', 
		'ps_grams_are_wet_weight', 
		'ps_mobile_racking', 
		'ps_crop', 
		'ps_crop_other', 
		'ps_avg_ceiling_height', 
		'ps_kwh_include_renewables', 
		'ps_lighting_power_density', 
		'ps_flower_canopy_size', 
		'ps_effic_hvac_orig', 
		'ps_tot_kw_peak', 
		'ps_no_natural_gas', 
		'ps_unit_natural_gas', 
		'ps_unit_wood', 
		'ps_unit_generator', 
		'ps_com_ma_id', 
		'ps_start_month', 
		'ps_kwh_tot_calc', 
		'ps_flower_weight_type', 
		'ps_tot_water', 
		'ps_tech_other', 
		'ps_tech_heat_pump', 
		'ps_grams_dry', 
		'ps_tot_kwh_renewable', 
		'ps_tot_natural_gas', 
		'ps_tot_generator', 
		'ps_tot_biofuel_wood', 
		'ps_tot_propane', 
		'ps_tot_fuel_oil', 
		'ps_tot_water_storage_source', 
		'ps_tot_water_storage_recirc', 
		'ps_tot_btu_non_electric', 
		'ps_lpd_clone', 
		'ps_lpd_veg', 
		'ps_lpd_flower', 
		'ps_hlpd_ma', 
		'ps_tot_waste_lbs',
		'ps_effic_prod_non', 
		'ps_effic_prod_non_status',
		'ps_effic_prod_all', 
		'ps_effic_prod_all_status',
		'ps_effic_fac_all', 
		'ps_effic_fac_all_status',
		'ps_unit_water',
		'ps_unit_distances', 
    ];
    
    // END SurvLoop auto-generated portion of Model
    
}
