<?php namespace App\Models;
// generated from /resources/views/vendor/survloop/admin/db/export-laravel-model-gen.blade.php

use Illuminate\Database\Eloquent\Model;

class RIIWaterBoardData extends Model
{
    protected $table      = 'rii_water_board_data';
    protected $primaryKey = 'wa_bo_da_id';
    public $timestamps    = true;
    protected $fillable   = 
    [    
		'wa_bo_da_date', 
		'wa_bo_da_farm_name', 
		'wa_bo_da_year', 
		'wa_bo_da_reporting', 
		'wa_bo_da_county', 
		'wa_bo_da_outdoor_canopy_area', 
		'wa_bo_da_outdoor_plant_count', 
		'wa_bo_da_outdoor_growing_medium', 
		'wa_bo_da_mixed_light_canopy_area', 
		'wa_bo_da_mixed_light_plant_count', 
		'wa_bo_da_mixed_light_growing_medium', 
		'wa_bo_da_indoor_canopy_area', 
		'wa_bo_da_indoor_plant_count', 
		'wa_bo_da_indoor_growing_medium', 
		'wa_bo_da_total_canopy_area', 
		'wa_bo_da_water_storage_cap_gal', 
		'wa_bo_da_water_storage_source_1', 
		'wa_bo_da_water_stored_source_1_jan', 
		'wa_bo_da_water_stored_source_1_feb', 
		'wa_bo_da_water_stored_source_1_mar', 
		'wa_bo_da_water_stored_source_1_apr', 
		'wa_bo_da_water_stored_source_1_may', 
		'wa_bo_da_water_stored_source_1_jun', 
		'wa_bo_da_water_stored_source_1_jul', 
		'wa_bo_da_water_stored_source_1_aug', 
		'wa_bo_da_water_stored_source_1_sep', 
		'wa_bo_da_water_stored_source_1_oct', 
		'wa_bo_da_water_stored_source_1_nov', 
		'wa_bo_da_water_stored_source_1_dec', 
		'wa_bo_da_water_storage_source_2', 
		'wa_bo_da_water_stored_source_2_jan', 
		'wa_bo_da_water_stored_source_2_feb', 
		'wa_bo_da_water_stored_source_2_mar', 
		'wa_bo_da_water_stored_source_2_apr', 
		'wa_bo_da_water_stored_source_2_may', 
		'wa_bo_da_water_stored_source_2_jun', 
		'wa_bo_da_water_stored_source_2_jul', 
		'wa_bo_da_water_stored_source_2_aug', 
		'wa_bo_da_water_stored_source_2_sep', 
		'wa_bo_da_water_stored_source_2_oct', 
		'wa_bo_da_water_stored_source_2_nov', 
		'wa_bo_da_water_stored_source_2_dec', 
		'wa_bo_da_water_storage_source_3', 
		'wa_bo_da_water_stored_source_3_jan', 
		'wa_bo_da_water_stored_source_3_feb', 
		'wa_bo_da_water_stored_source_3_mar', 
		'wa_bo_da_water_stored_source_3_apr', 
		'wa_bo_da_water_stored_source_3_may', 
		'wa_bo_da_water_stored_source_3_jun', 
		'wa_bo_da_water_stored_source_3_jul', 
		'wa_bo_da_water_stored_source_3_aug', 
		'wa_bo_da_water_stored_source_3_sep', 
		'wa_bo_da_water_stored_source_3_oct', 
		'wa_bo_da_water_stored_source_3_nov', 
		'wa_bo_da_water_stored_source_3_dec', 
		'wa_bo_da_water_application_source_1', 
		'wa_bo_da_water_applied_source_1_jan', 
		'wa_bo_da_water_applied_source_1_feb', 
		'wa_bo_da_water_applied_source_1_mar', 
		'wa_bo_da_water_applied_source_1_apr', 
		'wa_bo_da_water_applied_source_1_may', 
		'wa_bo_da_water_applied_source_1_jun', 
		'wa_bo_da_water_applied_source_1_jul', 
		'wa_bo_da_water_applied_source_1_aug', 
		'wa_bo_da_water_applied_source_1_sep', 
		'wa_bo_da_water_applied_source_1_oct', 
		'wa_bo_da_water_applied_source_1_nov', 
		'wa_bo_da_water_applied_source_1_dec', 
		'wa_bo_da_water_application_source_2', 
		'wa_bo_da_water_applied_source_2_jan', 
		'wa_bo_da_water_applied_source_2_feb', 
		'wa_bo_da_water_applied_source_2_mar', 
		'wa_bo_da_water_applied_source_2_apr', 
		'wa_bo_da_water_applied_source_2_may', 
		'wa_bo_da_water_applied_source_2_jun', 
		'wa_bo_da_water_applied_source_2_jul', 
		'wa_bo_da_water_applied_source_2_aug', 
		'wa_bo_da_water_applied_source_2_sep', 
		'wa_bo_da_water_applied_source_2_oct', 
		'wa_bo_da_water_applied_source_2_nov', 
		'wa_bo_da_water_applied_source_2_dec', 
		'wa_bo_da_water_application_source_3', 
		'wa_bo_da_water_applied_source_3_jan', 
		'wa_bo_da_water_applied_source_3_feb', 
		'wa_bo_da_water_applied_source_3_mar', 
		'wa_bo_da_water_applied_source_3_apr', 
		'wa_bo_da_water_applied_source_3_may', 
		'wa_bo_da_water_applied_source_3_jun', 
		'wa_bo_da_water_applied_source_3_jul', 
		'wa_bo_da_water_applied_source_3_aug', 
		'wa_bo_da_water_applied_source_3_sep', 
		'wa_bo_da_water_applied_source_3_oct', 
		'wa_bo_da_water_applied_source_3_nov', 
		'wa_bo_da_water_applied_source_3_dec', 
		'wa_bo_da_other_water_source', 
    ];
    
    // END Survloop auto-generated portion of Model
    
}
